baseURL = 'https://roneo.itcouldbewor.se/'
languageCode = 'en-us'
defaultContentLanguage = 'en'


[params]
  title = 'Cloverleaf Yarn'
  metaDescription = "Hugo + Netlify CMS + One click deploy to Netlify"


# Languages
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
mark = "EN"

[taxonomies]
  category= "theme"
  scene = "scenes"
